---
driver:
  name: vagrant
  synced_folders:
  - ["../", "/home/vagrant/workspace"]
  network:
  - ["forwarded_port", {guest: 9292, host: 3000}]
  - ["forwarded_port", {guest: 3000, host: 3000}]

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-14.04
    driver:
      box: trusty64

suites:
  - name: reviewsite
    run_list:
      - reviewsite
