---
driver:
  name: vagrant
  customize:
    memory: 1024
  synced_folders:
  - ["../", "/home/vagrant/workspace"]
  network:
  - ["forwarded_port", {guest: 9292, host: 3000}]
  - ["forwarded_port", {guest: 3000, host: 3000}]

provisioner:
  name: chef_solo

platforms:
  - name: kitchen-box
    driver:
      box: ubuntu/trusty64

suites:
  - name: reviewsite
    run_list:
      - reviewsite
